# -*- coding: utf-8 -*-
"""Appactividadess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oYrd_ecLGuOLfkPjO-ggfA2Y_vBNvnxC
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


st.image("imagen_app.png", width=300)

st.title("Predicción del Costo de Actividades")


df = pd.read_csv("Registroprogramacion.csv")


df['Fecha (dd/mm/aa)'] = pd.to_datetime(df['Fecha (dd/mm/aa)'], errors='coerce', dayfirst=True)

st.subheader("Datos originales")
st.dataframe(df)


columnas_necesarias = ["Presupuesto", "Tiempo invertido", "Tipo", "Momento", "No. de personas", "Costo"]

df = df.dropna(subset=columnas_necesarias)

st.subheader("Datos después de eliminar registros vacíos")
st.dataframe(df)


X = df[["Presupuesto", "Tiempo invertido", "Tipo", "Momento", "No. de personas"]]
y = df["Costo"]


categorical_cols = ["Tipo", "Momento"]
numeric_cols = ["Presupuesto", "Tiempo invertido", "No. de personas"]


preprocesador = ColumnTransformer([
    ("categoricas", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
    ("numericas", "passthrough", numeric_cols)
])


modelo = Pipeline([
    ("preprocesador", preprocesador),
    ("regresion", LinearRegression())
])


modelo.fit(X, y)

st.success("Modelo entrenado correctamente ")
\
st.subheader("Ingresa los datos para predecir el costo")

input_presupuesto = st.number_input("Presupuesto", min_value=0.0, step=1.0)
input_tiempo = st.number_input("Tiempo invertido (minutos)", min_value=0.0, step=1.0)
input_tipo = st.selectbox("Tipo de actividad", df["Tipo"].unique())
input_momento = st.selectbox("Momento", df["Momento"].unique())
input_personas = st.number_input("Número de personas", min_value=1, step=1)


if st.button("Predecir"):
    entrada = pd.DataFrame({
        "Presupuesto": [input_presupuesto],
        "Tiempo invertido": [input_tiempo],
        "Tipo": [input_tipo],
        "Momento": [input_momento],
        "No. de personas": [input_personas]
    })

    prediccion = modelo.predict(entrada)[0]

    st.metric("Costo estimado", f"${prediccion:,.2f}")